from . import res_config
from . import pos_config
from . import shift_config_settings
from . import product_product
from . import product_template
from . import pos_order_line
from . import pos_session
from . import pos_order
from . import pos_config_settings
from . import res_company
from . import pos_category
