from . import pos_config
from . import product_product
from . import product_template
from . import pos_order_line
from . import pos_session
from . import pos_order
from . import res_company
from . import pos_category
from . import stock_picking
from . import res_config_settings
from . import report_pos_order
from . import account_bank_statement
