language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0" WKHTMLTOPDF_VERSION="0.12.4"
  - TRANSIFEX_USER='transbot@druidoo.io'

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" LINT_CHECK="0"


install:
  - git clone --depth=1 https://github.com/druidoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
