language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

env:
  matrix:
    - COOP=lalouve ADDONS_DIR="louve_addons/ intercoop_addons/"
    - COOP=lacagette ADDONS_DIR="lacagette_addons/ louve_addons/ intercoop_addons/"
    - COOP=superquinquin ADDONS_DIR="intercoop_addons/ louve_addons/"

python:
  - "2.7"

virtualenv:
  system_site_packages: true

services:
  - postgresql

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - python-pychart
      - wkhtmltopdf
      - ttf-dejavu

install:
  - pip install coveralls
  - pip install flake8
  - python bootstrap.py
  - bin/buildout -c buildout_$COOP.cfg

script:
  - flake8 $ADDONS_DIR
  - createdb $COOP
  - psql $COOP -c 'CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;'
  - bin/upgrade_$COOP -d $COOP --init-load-demo-data
  - bin/nosetests -d $COOP -- -v -s $ADDONS_DIR --with-coverage

after_success:
  - coveralls
