language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

jobs:
  include:
    - stage: linting
      name: "LINT_CHECK"
      env:
        - LINT_CHECK="1"
    - stage: test
      env:
        - TESTS="1" MAKEPOT="1" WKHTMLTOPDF_VERSION="0.12.4"

env:
  global:
    - VERSION="12.0" ODOO_REPO="odoo/odoo" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

install:
  - git clone --depth=1 https://github.com/druidoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
