from . import product
from . import stock_inventory
from . import stock_inventory_line
from . import stock_picking
from . import stock_move
from . import stock_quant
from . import pos_order
from . import stock_move_line
from . import stock_inventory_valuation_view
from . import stock_inventory_valuation_report
