from . import mail_thread
from . import res_partner
from . import res_users
from . import shift_registration
from . import memberspace_conversation
from . import memberspace_alias
from . import shift_template
from . import proposal
from . import res_config_settings
from . import shift_shift
