# -*- coding: utf-8 -*-

from . import event_config_settings
from . import shift_leave_wizard
from . import barcode_rule
from . import res_partner
from . import res_partner_owned_share
from . import account_invoice
from . import capital_fundraising_category
from . import res_partner_generate_barcode_wizard
from . import shift_shift
from . import shift_template_registration
from . import shift_template
from . import shift_registration
from . import shift_extension
from . import shift_extension_type
from . import res_config
from . import res_users
from . import shift_leave_type
from . import shift_leave
from . import event
from . import event_registration
from . import event_event_ticket
from . import web_access_buttons
from . import shift_template_registration_line
from . import shift_ticket
from . import shift_holiday
from . import shift_counter_event
from . import shift_change_team
from . import res_company
from . import res_partner_inform
from . import shift_counter_reason
from . import mail_mass_mailing_contact
from . import shift_credit_config
from . import shift_mail_registration
from . import shift_template_operation
