# -*- coding: utf-8 -*-
from . import shift_leave_wizard
from . import barcode_rule
from . import res_partner
from . import res_partner_owned_share
from . import account_invoice
from . import capital_fundraising_category
from . import capital_fundraising_wizard
from . import res_partner_generate_barcode_wizard
from . import shift_shift
from . import shift_template_registration
from . import shift_template
from . import shift_registration
from . import shift_extension
from . import shift_extension_type
from . import res_config
from . import res_users
from . import shift_leave_type
from . import shift_leave
from . import event
from . import event_registration
from . import event_event_ticket
from . import web_access_buttons
