[tool.towncrier]
    template = "../.towncrier-template.rst"
    underlines = ['~']
    title_format = "{version} ({project_date})"
    issue_format = "`#{issue} <https://github.com/oca/mis-builder/issues/{issue}>`_"
    directory = "readme/newsfragments"
    filename = "readme/HISTORY.rst"
