from . import shift_mail
from . import shift_template_mail
from . import shift_registration
from . import shift_shift
from . import shift_template
from . import shift_template_registration
from . import shift_template_registration_line
from . import shift_type
from . import shift_ticket
from . import shift_template_ticket
from . import shift_mail_registration
from . import shift_extension
from . import shift_extension_type
from . import res_partner
from . import res_config_settings
from . import product
from . import shift_leave
from . import shift_leave_type
from . import shift_counter_event
