name: Odoo Addon Generate Readme

on:
  push:
    branches:
    - '[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
    - uses: nelonoel/branch-name@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install OCA Maintainer Tools
      run: |
        python -m pip install --upgrade pip
        pip install -e git+https://github.com/druidoo-dev/maintainer-tools.git@druidoo#egg=oca-maintainer-tools

    - name: Generate Readme
      run: |
        git config --local user.email ${{ secrets.BOT_GITHUB_EMAIL }}
        git config --local user.name ${{ secrets.BOT_GITHUB_USER }}
        wget -O ~/icon.png https://raw.githubusercontent.com/druidoo/druidoo-repo-sync/master/icon.png
        oca-gen-addons-table --commit
        oca-gen-addon-readme --addons-dir=. --org-name=${{ github.event.repository.owner.name }} --repo-name=${{ github.event.repository.name }} --branch=${BRANCH_NAME} --commit
        oca-gen-addon-icon --addons-dir=. --src-icon=$(realpath ~/icon.png) --commit
  
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
        branch: ${{ github.ref }}
